### ISSUE TITLE
Best way to set up data service with Iridium ... 

### ISSUE THREAD

**Issue by dwblair** [PaulZC/Iridium_9603_Beacon#1]
Hi Paul! 

Fantastic, inspiring project.  We're looking to deploy some environmental monitors in remote locations, and it looks like you've done all the hard design work for us already!  Thanks so much for sharing.

Quick question:  how did you end up setting up an "SBD" / Gateway service with Iridium?  Did you use a 9603 module + power circuitry PCB from a reseller, who then provided their own data service to you?

Cheers & thanks so much for your work.

**Comment by PaulZC** [comment]
Hi there,
I purchased the 9603 module from AST Systems in the UK and had them set up email forwarding for the SBD messages. They do offer an HTTP service too but I find email better suits my needs. I designed all of the power circuitry etc. myself - you can find full details in the Eagle directory or the pdf files in the repo.
If you want to carry on the conversation, you can contact me here:
https://www.dur.ac.uk/contactperson/?lid=1724
Enjoy!
Paul

**Comment by PaulZC** [comment]
Hi,
The Iridium 9603N Beacon repo has just had a major facelift. See https://github.com/PaulZC/Iridium_9603_Beacon/blob/master/LEARN.md for a more detailed description of the beacon - with pictures!
Enjoy!
Paul

**Comment by dwblair** [comment]
Paul,

Thanks so much for the revised presentation -- very thoughtful and thorough.  This is really impressive work, and I hope to dig into this week to understand it better.  And -- those light-weight, flexible solar panels are gorgeous :) 

Thanks for sharing all of this functionality with the community.  Huge help. 

Cheers,
Don
