### ISSUE TITLE
Iridium RX line held high.

### ISSUE THREAD

**Issue by keitarusm** [PaulZC/Iridium_9603_Beacon#2]
Hi, Paul

I've been following your work for a while now and I really want to thank you for your contributions. I've adapted your beacon for use in a sea-ice monitoring buoy. I'm having an issue right now where the RX line of the modem is being held high, the samd21 can't communicate with the modem. For diagnosing this issue I've verified that when the modem is powered down the samd21 can successfully transmit on this line, and similarly if the iridium sleep and 5V are powered on but the modem is not in the socket, then the samd21 can transmit. 

I'm certainly not asking you to deep dive on this issue, just wondering if you've seen it before and maybe know the boneheaded mistake I've made. Either way, once I've figured it out I will post the solution here in case it's helpful to anyone else following along with your work.

Again, great stuff. Following your notes on adapting things for this microprocessor has been really instrumental to moving my own work along. My project is also to be released under the same license as yours, just as soon as it actually does something and is useful to the community. 

V/r
James Whitlock

**Comment by PaulZC** [comment]
Hi James,
I'm very glad you're finding the Beacon design useful.
Can you send me a message via [this link](https://www.dur.ac.uk/contactperson/?lid=1724) so we can take the discussion off-line for now, then - as you suggest - update this issue with the solution.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Actually, one thing to check first is:
The TX/RX pins on the 9603N can be confusing... They use old-school DCE notation.
Pin 6 is called "DF_S_TX" but is actually the receive data INPUT. You need to connect this to your SAMD21 Tx pin.
Likewise pin 7 is called "DF_S_RX" but is actually the serial data OUTPUT. You need to connect this to your SAMD21 Rx pin.
If it's not that, then let's continue off-line...

**Comment by keitarusm** [comment]
Paul,
This exactly. I should have read the data sheet more carefully. Live and learn. Thank you for the reply.

-James
