### ISSUE TITLE
Is a super capacitor really needed?

### ISSUE THREAD

**Issue by saffetblt** [PaulZC/Iridium_9603_Beacon#3]
Hello Paul,
I like your work, congratulations. I have a question for you. Do you really need a Supercapacitor when using Iridium? I see that 3 serial Energyzer L92 can handle peak currents. Is there something I missed?

Thanks in advance for your answer.

**Comment by PaulZC** [comment]
Hello Saffet (@saffetblt ),

The 9603N modem needs 5.0V +/- 10% and draws a peak current of 1.3A when it is transmitting. So long as your power circuit can deliver that then you are good to go.

The super capacitors are useful as they can be charged up slowly from a low current source (such as a solar panel) and then deliver the 1.3A when needed. The charging circuit also "steps up" the battery voltage, charging the capacitors to 5.3V. If the batteries get really cold (on a balloon flight) the voltage will fall to about 1.1V per cell. The charging circuit still works, stepping up 3.3V to 5.3V.

On some of my other designs, I used a PP3 (9V) battery and a 5V switching regulator to deliver the current. See:

https://github.com/PaulZC/Iridium_9603N_Mini_Beacon

Good luck with your project!

Best wishes,
Paul
